version: "2.4"

services:

    openssh-server:
        image: ghcr.io/linuxserver/openssh-server
        container_name: openssh-server
        hostname: openssh-server
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - SUDO_ACCESS=true
            - PASSWORD_ACCESS=true
            - USER_PASSWORD=edge
            - USER_NAME=edge
        volumes:
            - ./config/openssh-server:/config
            - type: volume
              source: nfs_volume
              target: /nfs # where the folder will be mounted inside container
    
        ports:
            - 45555:2222
        restart: unless-stopped
        mem_limit: 100mb

volumes:
    
    nfs_volume:
        driver_opts:
            type: "nfs"
            o: "addr=192.168.178.6,nolock,soft,rw" # server's IP address
            device: ":/nfs/shared" # location of the folder on the server